Create a6.is-cool.me.json
is-cool-me/register pull request #146
Opened 2024-07-21 16:09 UTC by aaron2305

## Requirements
- [x] You have completed your website.
- [x] The website is reachable.
- [x] The CNAME record doesn't contain `https://` or `/`.  
- [x] There is sufficient information at the `owner` field.

## Description

to live stream a football match or game 
## Link to Website

http://testingaktv.atwebpages.com/login.php

2024-07-22 09:14 UTC, LightHostingFree requested changes

2024-07-22 09:14 UTC, LightHostingFree commented on domains/a6.is-cool.me.json
> +
add }, here

2024-07-22 09:14 UTC, LightHostingFree commented on domains/a6.is-cool.me.json
> +
And accept the CLA

2024-07-23 15:58 UTC, aaron2305 commented
I have read the CLA Document and I hereby sign the CLA

2024-07-24 07:16 UTC, LightHostingFree commented
I have corrected your json file. Enjoy your free subdomain!

2024-07-24 07:22 UTC, ShamyakGoel approved these changes

2024-07-24 07:23 UTC, LightHostingFree approved these changes

2024-07-24 07:23 UTC, merged