Register telegram.is-app.tech
is-cool-me/register pull request #39
Opened 2024-02-04 12:02 UTC by RyanisyydsTT

Added `telegram.is-app.tech` using the [CLI](https://cli.is-cool.me).

2024-02-04 12:02 UTC, RyanisyydsTT commented
I have read the CLA Document and I hereby sign the CLA

2024-02-04 12:02 UTC, LightHostingFree approved these changes

2024-02-05 02:44 UTC, LightHostingFree commented
recheck

2024-02-05 02:46 UTC, LightHostingFree requested changes
Invalid A record

2024-02-05 07:09 UTC, closed without merging