Register ycanyaz.is-app.tech
is-cool-me/register pull request #51
Opened 2024-02-26 20:09 UTC by ycanyaz8

Added `ycanyaz.is-app.tech` using the [CLI](https://cli.is-cool.me).

2024-02-26 20:09 UTC, ycanyaz8 commented
I have read the CLA Document and I hereby sign the CLA

2024-02-26 20:09 UTC, LightHostingFree approved these changes

2024-02-27 01:44 UTC, LightHostingFree commented
recheck

2024-02-27 02:17 UTC, LightHostingFree requested changes
Cname record can't be blank.

2024-03-06 06:44 UTC, closed without merging